name: Swift MacOS X86_64

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  macOS-swift:
    runs-on: macos-latest
    strategy:
      matrix:
        swift_version: [5.1.5-bionic, 5.2.3-bionic, 5.3.1-bionic]
        xcode_version: [Xcode_11.3.1.app, Xcode_11.4.app, Xcode_12.app]
    steps:
    - uses: actions/checkout@v2
    - name: Xcode Version
      run: |
        sudo xcode-select -s /Applications/${{ matrix.xcode_version }}
        xcodebuild -version
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build
    - name: Test
      run: swift test --enable-test-discovery
