name: Swift MacOS X86_64

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  macOS-xcode:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode_version: [11.3.1, 11.4, 12]
    steps:
    - uses: actions/checkout@v2
    - name: Xcode Version
      run: |
        sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode_version }}.app
        xcodebuild -version
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build
    - name: Test
      run: swift test --enable-test-discovery
